version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 5s
        timeout: 5s
        retries: 3

  frontend:
    build: ./frontend
    container_name: gradio-ui
    command: python3 main.py
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - BACKEND_PORT
      - FRONTEND_PORT
  
  db:
    image: mongo:6-jammy
    container_name: mongo-result-backend
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
  
  worker:
    build: ./worker
    container_name: worker
    command: celery -A celeryworker.app worker -l warning
    # volumes:
    #   - ./worker:/app
    #   - /app/models
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - CLIP_MODEL
    depends_on:
      rabbitmq:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: fastapi-backend
    image: backend
    command: uvicorn app:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    depends_on:
      - worker

  flower:
    image: mher/flower:2.0
    environment:
      - CELERY_BROKER_URL
      - FLOWER_PORT
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - worker
      - db